[package]
name = "Modint"
version = "0.1.0"
authors = ["namacha <thdyk.4.11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
